@startuml
start

:Получена базовая котировка \nиз топика Kafka ACP.BASE_QUOTES.AVRO;
:Получить все группы, \nгде заданы настройки \nтриггеров по валютной паре;

if (Котировка введена руками?) then (да)
  :Рассчитать и опубликовать;
else (нет)
  if (Есть предыдущая базовая котировка?) then (Да)
    :Взять предыдущую базовую котировку;
    partition #lightGreen Триггер {
    while (Есть в списке группа на обработку?) is (Да)
        if (настройки bid == offer == null?) then (Да)
              :Хотя бы одна настройка должна быть определена;
              stop
        else (Хотя бы одна настройка определена)
            if (Есть отклонение по bid/offer?) then (ДА)
                    :Запустить триггер для валютной пары в группе;
                    while (Пока таймер по триггеру не истёк) is (Нет)
                      fork
                         :Сравнить каждую новую базовую котировку\nс базовой до запуска триггера;
                         if (Отклонение сохраняется?) then (Да)
                              :Слушаем поток котировок;
                         else (Нет)
                              :Процесс по триггеру немедленно останавливается;
                              :Обработка котировки завершена;
                              stop;
                         endif
                      end fork
                    endwhile (Да)
                else (Нет)
                    :Обработка котировки завершена;
                    stop;
            endif
        endif
    endwhile (Нет)
    }
  else (нет)
  endif
endif


while (Есть необработанная группа?) is (да)
  partition #orange Расчёт цен и формирование котировки {
    :Посчитать новую расчётную котировку \nдля валютной пары по ЦУ;
  }
  :Сохранить базовую котировку и расчётную для группы;
endwhile (нет)

:Расчётные котировки сформированы;
partition #lightBlue Блокировка тиража {
if (Есть ранее посчитанная расчётная котировка?) then(Дa)
   if (Предыдущая котировка ожидает подтверждения от БА?) then( Да )
        stop
   else (Нет)
       if (Цена текущей котировки в пределах отклонения?) then (Да)
       else (Нет)
           :Формируется и отправляется метрика \nоб отклонении в Тенгри;
           :Тираж блокируется;
           stop
       endif
   endif
else (Нет)
     :Расчётная котировка заносится в буфер \nи ожидает подтверждения от БА;
     stop
endif
}
:Сгруппировать котировки по ЦУ \nи сформировать по каждому ЦУ сообщения;
:Отправить сообщения в топик \nKafka ACP.CALCULATED_QUOTES.AVRO;
stop

@enduml